/**
 * File: google_app_scripts/1N6o00/process_currency_definitions_telegram_logs.js
 * Repository: https://github.com/TrueSightDAO/tokenomics
 * Apps Script editor:
 * https://script.google.com/home/projects/1N6o00N9VtRK_L3e0NQXEsmC6QME1KObZdmdbJgo0Tbgj_7P-ElNL5THn/edit
 *
 * Description: Processes [CURRENCY DEFINITION EVENT] submissions from Telegram
 * Chat Logs, validates them against contributor signatures, and appends a row
 * to the Currencies tab (cols A–L) in the Main Ledger. After insert, sorts
 * A→Z by column A so the new SKU is immediately QR-ready.
 *
 * Submission format expected (generated by truesight-dao-define-currency CLI):
 *
 *   [CURRENCY DEFINITION EVENT]
 *   - Currency: Ceremonial Cacao (250g)
 *   - Price in USD: 25.00
 *   - Serializable: TRUE
 *   - Product Image: https://...
 *   - Landing Page: https://truesight.me/shop/ceremonial-cacao
 *   - Ledger: AGROVERSE
 *   - Farm Name: Fazenda Rendimento
 *   - State: Bahia
 *   - Country: Brazil
 *   - Year: 2026
 *   - Unit Weight (grams): 250
 *   - Unit Weight (ounces): 8.82
 *   --------
 *
 *   My Digital Signature: <pubkey>
 *   Request Transaction ID: <hash>
 *
 * Edgar webhook hookup: doGet(?action=processCurrencyDefinitionsFromTelegramChatLogs)
 * is defined at the bottom so sentiment_importer's trigger_immediate_processing
 * branch for [CURRENCY DEFINITION EVENT] can fire processing in seconds.
 */

// ============================================================================
// CONSTANTS
// ============================================================================

/** Sheet name on the Main Ledger where currency definitions land. */
const CURRENCIES_SHEET_NAME = 'Currencies';

/** Main Ledger spreadsheet (same as CONTRIBUTORS_SHEET_URL). */
const MAIN_LEDGER_URL = 'https://docs.google.com/spreadsheets/d/1GE7PUq-UT6x2rBN-Q2ksogbWpgyuh2SaxJyG_uEK6PU/edit';

/** Telegram Chat Logs workbook. */
const TELEGRAM_LOGS_URL = 'https://docs.google.com/spreadsheets/d/1qbZZhf-_7xzmDTriaJVWj6OZshyQsFkdsAV8-pyzASQ/edit';

/** Telegram Chat Logs sheet name. */
const TELEGRAM_LOGS_SHEET = 'Telegram Chat Logs';

/** Contributors Digital Signatures sheet name. */
const CONTRIBUTORS_SIGNATURES_SHEET = 'Contributors Digital Signatures';

// Column indices for Telegram Chat Logs (0-based) — shared with other processors
const TELEGRAM_UPDATE_ID_COL = 0;
const TELEGRAM_CHATROOM_ID_COL = 1;
const TELEGRAM_CHATROOM_NAME_COL = 2;
const TELEGRAM_MESSAGE_ID_COL = 3;
const TELEGRAM_CONTRIBUTOR_NAME_COL = 4;
const TELEGRAM_MESSAGE_COL = 6;
const TELEGRAM_STATUS_COL = 9;

// ============================================================================
// PARSING
// ============================================================================

/**
 * Extracts currency definition details from a [CURRENCY DEFINITION EVENT] message.
 * Matches the 12 canonical labels from the CLI (cols A–L of Currencies tab).
 */
function parseCurrencyDefinitionMessage(message) {
  const details = {
    currency: null,
    priceInUsd: null,
    serializable: null,
    productImage: null,
    landingPage: null,
    ledger: null,
    farmName: null,
    state: null,
    country: null,
    year: null,
    unitWeightGrams: null,
    unitWeightOunces: null,
    digitalSignature: null,
    requestTransactionId: null
  };

  try {
    const currencyMatch = message.match(/- Currency:\s*([^\n]+)/i);
    if (currencyMatch) details.currency = currencyMatch[1].trim();

    const priceMatch = message.match(/- Price in USD:\s*\$?([0-9,]*\.?[0-9]+)/i);
    if (priceMatch) details.priceInUsd = parseFloat(priceMatch[1].replace(/,/g, ''));

    const serializableMatch = message.match(/- Serializable:\s*([^\n]+)/i);
    if (serializableMatch) details.serializable = serializableMatch[1].trim().toUpperCase();

    const productImageMatch = message.match(/- Product Image:\s*([^\n]+)/i);
    if (productImageMatch) details.productImage = productImageMatch[1].trim();

    const landingPageMatch = message.match(/- Landing Page:\s*([^\n]+)/i);
    if (landingPageMatch) details.landingPage = landingPageMatch[1].trim();

    const ledgerMatch = message.match(/- Ledger:\s*([^\n]+)/i);
    if (ledgerMatch) details.ledger = ledgerMatch[1].trim();

    const farmNameMatch = message.match(/- Farm Name:\s*([^\n]+)/i);
    if (farmNameMatch) details.farmName = farmNameMatch[1].trim();

    const stateMatch = message.match(/- State:\s*([^\n]+)/i);
    if (stateMatch) details.state = stateMatch[1].trim();

    const countryMatch = message.match(/- Country:\s*([^\n]+)/i);
    if (countryMatch) details.country = countryMatch[1].trim();

    const yearMatch = message.match(/- Year:\s*([^\n]+)/i);
    if (yearMatch) details.year = yearMatch[1].trim();

    const unitWeightGramsMatch = message.match(/- Unit Weight \(grams\):\s*([0-9,]*\.?[0-9]+)/i);
    if (unitWeightGramsMatch) details.unitWeightGrams = parseFloat(unitWeightGramsMatch[1].replace(/,/g, ''));

    const unitWeightOuncesMatch = message.match(/- Unit Weight \(ounces\):\s*([0-9,]*\.?[0-9]+)/i);
    if (unitWeightOuncesMatch) details.unitWeightOunces = parseFloat(unitWeightOuncesMatch[1].replace(/,/g, ''));

    // Digital signature and request transaction ID
    const sigPattern = /My Digital Signature:\s*([\s\S]*?)(?:\n\s*Request Transaction ID:|$)/i;
    const sigMatch = message.match(sigPattern);
    if (sigMatch) details.digitalSignature = sigMatch[1].trim();

    const requestIdMatch = message.match(/Request Transaction ID:\s*([^\n]+)/i);
    if (requestIdMatch) details.requestTransactionId = requestIdMatch[1].trim();

    Logger.log('Parsed currency definition: ' + (details.currency || '(unknown)'));
  } catch (e) {
    Logger.log('Error parsing currency definition message: ' + e.message);
  }

  return details;
}

// ============================================================================
// DEDUP (check if already recorded)
// ============================================================================

/**
 * Check if a currency definition record already exists in the Currencies tab
 * by matching the currency name (column A). Returns true if found.
 */
function currencyDefinitionRecordExists(currencyName) {
  try {
    const spreadsheet = SpreadsheetApp.openByUrl(MAIN_LEDGER_URL);
    const sheet = spreadsheet.getSheetByName(CURRENCIES_SHEET_NAME);
    if (!sheet) return false;

    const data = sheet.getDataRange().getValues();
    const headerRow = 0; // Row 1 (0-based index 0) is the header

    for (let i = headerRow + 1; i < data.length; i++) {
      const row = data[i];
      const existingName = row[0] ? String(row[0]).trim().toLowerCase() : '';
      if (existingName === currencyName.trim().toLowerCase()) {
        Logger.log('Currency definition already exists: ' + currencyName);
        return true;
      }
    }
    return false;
  } catch (e) {
    Logger.log('Error checking for existing currency definition: ' + e.message);
    return false;
  }
}

// ============================================================================
// INSERT ROW INTO CURRENCIES TAB
// ============================================================================

/**
 * Appends a new row to the Currencies tab with the parsed fields.
 * Columns A–L map to:
 *   A = Currency
 *   B = Price in USD
 *   C = Serializable
 *   D = Product Image
 *   E = Landing Page
 *   F = Ledger
 *   G = Farm Name
 *   H = State
 *   I = Country
 *   J = Year
 *   K = Unit Weight (grams)
 *   L = Unit Weight (ounces)
 *
 * @returns {boolean} true if the row was inserted
 */
function insertCurrencyDefinitionRecord(details) {
  try {
    const spreadsheet = SpreadsheetApp.openByUrl(MAIN_LEDGER_URL);
    const sheet = spreadsheet.getSheetByName(CURRENCIES_SHEET_NAME);
    if (!sheet) {
      Logger.log('ERROR: Currencies sheet not found');
      return false;
    }

    const newRow = [
      details.currency || '',
      details.priceInUsd || '',
      details.serializable || 'TRUE',
      details.productImage || '',
      details.landingPage || '',
      details.ledger || '',
      details.farmName || '',
      details.state || '',
      details.country || '',
      details.year || '',
      details.unitWeightGrams || '',
      details.unitWeightOunces || ''
    ];

    sheet.appendRow(newRow);
    Logger.log('Inserted currency definition: ' + (details.currency || '(unknown)'));
    return true;
  } catch (e) {
    Logger.log('Error inserting currency definition record: ' + e.message);
    return false;
  }
}

// ============================================================================
// SORT CURRENCIES TAB A→Z
// ============================================================================

/**
 * Sorts the Currencies tab A→Z by column A (Currency name), skipping the
 * header row. Called after every insert so the new SKU lands in the right
 * alphabetical position and is immediately findable.
 */
function sortCurrenciesAZ() {
  try {
    const spreadsheet = SpreadsheetApp.openByUrl(MAIN_LEDGER_URL);
    const sheet = spreadsheet.getSheetByName(CURRENCIES_SHEET_NAME);
    if (!sheet) {
      Logger.log('ERROR: Currencies sheet not found for sort');
      return;
    }

    const lastRow = sheet.getLastRow();
    if (lastRow <= 1) return; // Header only or empty

    // Sort range A2:L{lastRow} by column A ascending
    const range = sheet.getRange(2, 1, lastRow - 1, 12);
    range.sort({ column: 1, ascending: true });
    Logger.log('Sorted Currencies tab A→Z');
  } catch (e) {
    Logger.log('Error sorting Currencies tab: ' + e.message);
  }
}

// ============================================================================
// MAIN PROCESSOR
// ============================================================================

/**
 * Scans Telegram Chat Logs for rows with status PROCESSING that contain
 * [CURRENCY DEFINITION EVENT], validates the digital signature, and inserts
 * a row into the Currencies tab.
 *
 * Called by:
 *   1. Edgar webhook: doGet(?action=processCurrencyDefinitionsFromTelegramChatLogs)
 *   2. Time-driven trigger (10-min cron fallback)
 */
function processCurrencyDefinitionsFromTelegramChatLogs() {
  Logger.log('=== processCurrencyDefinitionsFromTelegramChatLogs started ===');

  try {
    const spreadsheet = SpreadsheetApp.openByUrl(TELEGRAM_LOGS_URL);
    const sheet = spreadsheet.getSheetByName(TELEGRAM_LOGS_SHEET);
    if (!sheet) {
      Logger.log('ERROR: Telegram Chat Logs sheet not found');
      return;
    }

    const lastRow = sheet.getLastRow();
    if (lastRow < 2) {
      Logger.log('No data rows in Telegram Chat Logs');
      return;
    }

    // Read all data rows (columns A–J, 0-based indices 0–9)
    const data = sheet.getRange(2, 1, lastRow - 1, 10).getValues();
    let processedCount = 0;
    let skippedCount = 0;

    for (let i = 0; i < data.length; i++) {
      const row = data[i];
      const message = row[TELEGRAM_MESSAGE_COL] ? String(row[TELEGRAM_MESSAGE_COL]) : '';

      // Only process rows with [CURRENCY DEFINITION EVENT]
      if (message.indexOf('[CURRENCY DEFINITION EVENT]') === -1) {
        continue;
      }

      // Only process rows with status PROCESSING
      const status = row[TELEGRAM_STATUS_COL] ? String(row[TELEGRAM_STATUS_COL]).trim() : '';
      if (status !== 'PROCESSING') {
        Logger.log('Skipping row ' + (i + 2) + ': status is ' + status + ' (not PROCESSING)');
        skippedCount++;
        continue;
      }

      const updateId = row[TELEGRAM_UPDATE_ID_COL];
      const messageId = row[TELEGRAM_MESSAGE_ID_COL];
      Logger.log('Processing row ' + (i + 2) + ': update_id=' + updateId + ' message_id=' + messageId);

      // Parse the message
      const details = parseCurrencyDefinitionMessage(message);

      if (!details.currency) {
        Logger.log('Skipping row ' + (i + 2) + ': Could not parse Currency field');
        skippedCount++;
        continue;
      }

      if (!details.digitalSignature) {
        Logger.log('Skipping row ' + (i + 2) + ': No digital signature found');
        skippedCount++;
        continue;
      }

      // Validate digital signature against Contributors Digital Signatures
      const sigResult = findContributorByDigitalSignature(details.digitalSignature);
      if (!sigResult.contributorName) {
        Logger.log('Skipping row ' + (i + 2) + ': ' + sigResult.error);
        skippedCount++;
        continue;
      }

      // Check for duplicates by currency name
      if (currencyDefinitionRecordExists(details.currency)) {
        Logger.log('Skipping row ' + (i + 2) + ': Currency "' + details.currency + '" already exists');
        skippedCount++;
        continue;
      }

      // Insert the record
      const success = insertCurrencyDefinitionRecord(details);
      if (success) {
        processedCount++;
      } else {
        skippedCount++;
      }
    }

    Logger.log('Processing complete: ' + processedCount + ' currency definitions recorded, ' + skippedCount + ' skipped');

    // Sort after inserts so the new SKU is immediately findable
    if (processedCount > 0) {
      sortCurrenciesAZ();
    }
  } catch (e) {
    Logger.log('ERROR in processCurrencyDefinitionsFromTelegramChatLogs: ' + e.message);
  }
}

// ============================================================================
// TEST FUNCTIONS
// ============================================================================

function testParseCurrencyDefinitionMessage() {
  const testMessage = '[CURRENCY DEFINITION EVENT]\n' +
    '- Currency: Ceremonial Cacao (250g)\n' +
    '- Price in USD: 25.00\n' +
    '- Serializable: TRUE\n' +
    '- Product Image: https://example.com/img.jpg\n' +
    '- Landing Page: https://truesight.me/shop/ceremonial-cacao\n' +
    '- Ledger: AGROVERSE\n' +
    '- Farm Name: Fazenda Rendimento\n' +
    '- State: Bahia\n' +
    '- Country: Brazil\n' +
    '- Year: 2026\n' +
    '- Unit Weight (grams): 250\n' +
    '- Unit Weight (ounces): 8.82\n' +
    '--------\n' +
    '\n' +
    'My Digital Signature: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA...\n' +
    '\n' +
    'Request Transaction ID: abc123xyz\n';  

  const details = parseCurrencyDefinitionMessage(testMessage);

  Logger.log('=== Parsed Currency Definition Details ===');
  Logger.log('Currency: ' + details.currency);
  Logger.log('Price in USD: ' + details.priceInUsd);
  Logger.log('Serializable: ' + details.serializable);
  Logger.log('Product Image: ' + details.productImage);
  Logger.log('Landing Page: ' + details.landingPage);
  Logger.log('Ledger: ' + details.ledger);
  Logger.log('Farm Name: ' + details.farmName);
  Logger.log('State: ' + details.state);
  Logger.log('Country: ' + details.country);
  Logger.log('Year: ' + details.year);
  Logger.log('Unit Weight (grams): ' + details.unitWeightGrams);
  Logger.log('Unit Weight (ounces): ' + details.unitWeightOunces);
  Logger.log('Digital Signature: ' + (details.digitalSignature ? details.digitalSignature.substring(0, 50) + '...' : 'None'));
  Logger.log('Request Transaction ID: ' + details.requestTransactionId);
}

// ============================================================================
// EDGAR WEBHOOK ENTRY POINT
// ============================================================================

/**
 * doGet — invoked by sentiment_importer's trigger_immediate_processing branch
 * for [CURRENCY DEFINITION EVENT] submissions, so processing happens in seconds
 * instead of waiting for the time-driven cron trigger.
 *
 * Edgar config: sentiment_importer/config/application.rb
 *   config.currency_definition_processing_webhook_url
 *
 * Trigger URL shape:
 *   https://script.google.com/macros/s/<deployment>/exec?action=processCurrencyDefinitionsFromTelegramChatLogs
 */
function doGet(e) {
  const action = (e && e.parameter && e.parameter.action) || '';
  Logger.log('doGet called with action: ' + (action || 'none'));

  if (action === 'processCurrencyDefinitionsFromTelegramChatLogs') {
    try {
      Logger.log('Webhook triggered: processCurrencyDefinitionsFromTelegramChatLogs');
      processCurrencyDefinitionsFromTelegramChatLogs();
      Logger.log('Webhook processing completed successfully');
      return ContentService
        .createTextOutput('\u2705 Currency definitions processed successfully. Check execution logs for details.')
        .setMimeType(ContentService.MimeType.TEXT);
    } catch (e) {
      Logger.log('Webhook processing failed: ' + e.message);
      return ContentService
        .createTextOutput('\u274c Error: ' + e.message)
        .setMimeType(ContentService.MimeType.TEXT);
    }
  }

  // Fallback: return help text
  return ContentService
    .createTextOutput(
      'Currency Definition Processor is running.\n' +
      'Available actions:\n' +
      '  ?action=processCurrencyDefinitionsFromTelegramChatLogs  - Process pending currency definitions\n'
    )
    .setMimeType(ContentService.MimeType.TEXT);
}
