name: QR Code Generation Webhook

on:
  # Trigger via repository_dispatch (external webhook)
  repository_dispatch:
    types: [qr-code-generation]
  
  # Trigger via workflow_dispatch (manual trigger)
  workflow_dispatch:
    inputs:
      product_name:
        description: 'Product name to generate QR code for'
        required: true
        type: string
      google_script_url:
        description: 'Google App Script URL (optional)'
        required: false
        type: string
      no_commit:
        description: 'Skip committing to repository'
        required: false
        type: boolean
        default: false

env:
  PYTHON_VERSION: '3.9'

jobs:
  generate-qr-code:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout tokenomics repository (code)
      uses: actions/checkout@v4
      with:
        repository: TrueSightDAO/tokenomics
        token: ${{ secrets.GITHUB_TOKEN }}
        path: tokenomics
    
    - name: Checkout qr_codes repository (assets)
      uses: actions/checkout@v4
      with:
        repository: TrueSightDAO/qr_codes
        token: ${{ secrets.GITHUB_TOKEN }}
        path: qr_codes
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install qrcode[pil] requests pillow
    
    - name: Extract product name from webhook
      id: extract-product
      run: |
        if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
          echo "product_name=${{ github.event.client_payload.product_name }}" >> $GITHUB_OUTPUT
          echo "landing_page_url=${{ github.event.client_payload.landing_page_url || '' }}" >> $GITHUB_OUTPUT
          echo "no_commit=${{ github.event.client_payload.no_commit || 'false' }}" >> $GITHUB_OUTPUT
        else
          echo "product_name=${{ github.event.inputs.product_name }}" >> $GITHUB_OUTPUT
          echo "landing_page_url=${{ github.event.inputs.landing_page_url || '' }}" >> $GITHUB_OUTPUT
          echo "no_commit=${{ github.event.inputs.no_commit || 'false' }}" >> $GITHUB_OUTPUT
        fi
    
    - name: Generate QR Code
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: TrueSightDAO/qr_codes
        GITHUB_WORKSPACE: qr_codes
      run: |
        # Debug: Check what directories exist
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        
        echo "Checking if qr_codes directory exists:"
        ls -la qr_codes/ || echo "qr_codes directory not found!"
        
        # Copy the Python script to the qr_codes directory
        cp tokenomics/agroverse_qr_code_web_service/github_webhook_handler.py qr_codes/
        
        # Change to qr_codes directory
        cd qr_codes
        
        echo "Now in qr_codes directory: $(pwd)"
        echo "qr_codes directory contents:"
        ls -la
        
        # Create a temporary script to handle arguments properly
        cat > run_webhook.sh << 'EOF'
        #!/bin/bash
        set -e
        
        PRODUCT_NAME="$1"
        OUTPUT_FILE="$2"
        LANDING_PAGE_URL="$3"
        NO_COMMIT="$4"
        
        CMD="python github_webhook_handler.py \"$PRODUCT_NAME\" --output-file \"$OUTPUT_FILE\""
        
        if [ -n "$LANDING_PAGE_URL" ]; then
          CMD="$CMD --landing-page-url \"$LANDING_PAGE_URL\""
        fi
        
        if [ "$NO_COMMIT" = "true" ]; then
          CMD="$CMD --no-commit"
        fi
        
        echo "Running: $CMD"
        eval $CMD
        EOF
        
        chmod +x run_webhook.sh
        
        # Run the webhook handler
        ./run_webhook.sh \
          "${{ steps.extract-product.outputs.product_name }}" \
          "results.json" \
          "${{ steps.extract-product.outputs.landing_page_url }}" \
          "${{ steps.extract-product.outputs.no_commit }}"
        
        # Copy results back to tokenomics directory for artifact upload
        cp results.json ../tokenomics/agroverse_qr_code_web_service/
        
        # Display results
        cat results.json
    
    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: qr-code-results
        path: tokenomics/agroverse_qr_code_web_service/results.json
    
    - name: Comment on issue (if triggered from issue)
      if: github.event_name == 'repository_dispatch' && github.event.client_payload.issue_number
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const results = JSON.parse(fs.readFileSync('tokenomics/agroverse_qr_code_web_service/results.json', 'utf8'));
          
          let comment = `## QR Code Generation Results\n\n`;
          
          if (results.success) {
            comment += `✅ **Success!** QR code generated for product: \`${results.product.product_name}\`\n\n`;
            comment += `**QR Code:** \`${results.qr_code}\`\n`;
            comment += `**GitHub URL:** ${results.github_url}\n`;
            comment += `**Sheet Row:** ${results.row_added}\n`;
            comment += `**Timestamp:** ${results.timestamp}\n`;
          } else {
            comment += `❌ **Error:** ${results.error}\n\n`;
            comment += `**Product:** ${results.product_name}\n`;
            comment += `**Timestamp:** ${results.timestamp}\n`;
          }
          
          github.rest.issues.createComment({
            issue_number: ${{ github.event.client_payload.issue_number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
